export interface TemplateNode {
  id: string;
  label: string;
  shape: "rect" | "rounded" | "circle" | "diamond" | "hexagon" | "parallelogram" | "triangle" | "cylinder" | "cloud" | "process" | "decision";
  bgColor: string;
}

export interface TemplateEdge {
  id: string;
  source: string;
  target: string;
  label?: string;
}

export interface DiagramTemplate {
  id: string;
  title: string;
  description: string;
  category: string;
  color: string;
  nodeCount: number;
  previewNodes: { x: number; y: number; w: number }[];
  previewEdges: [number, number][];
  nodes: TemplateNode[];
  edges: TemplateEdge[];
}

// ── Family Trees ──────────────────────────────────────────────────────────────

const familyTreeBasic: DiagramTemplate = {
  id: "family-basic",
  title: "Basic Family Tree",
  description: "3-generation family tree with grandparents, parents and children.",
  category: "Family Trees",
  color: "#a78bfa",
  nodeCount: 8,
  previewNodes: [
    { x: 35, y: 15, w: 60 }, { x: 65, y: 15, w: 60 },
    { x: 25, y: 50, w: 55 }, { x: 75, y: 50, w: 55 },
    { x: 15, y: 85, w: 45 }, { x: 38, y: 85, w: 45 }, { x: 62, y: 85, w: 45 }, { x: 85, y: 85, w: 45 },
  ],
  previewEdges: [[0,2],[1,2],[0,3],[1,3],[2,4],[2,5],[3,6],[3,7]],
  nodes: [
    { id: "f1", label: "Grandfather\nJohn", shape: "rounded", bgColor: "#3730a3" },
    { id: "f2", label: "Grandmother\nMary", shape: "rounded", bgColor: "#5b21b6" },
    { id: "f3", label: "Father\nRobert", shape: "rect", bgColor: "#4c1d95" },
    { id: "f4", label: "Mother\nSusan", shape: "rect", bgColor: "#4c1d95" },
    { id: "f5", label: "Emily", shape: "rounded", bgColor: "#6d28d9" },
    { id: "f6", label: "James", shape: "rounded", bgColor: "#6d28d9" },
    { id: "f7", label: "Sophia", shape: "rounded", bgColor: "#6d28d9" },
    { id: "f8", label: "Liam", shape: "rounded", bgColor: "#6d28d9" },
  ],
  edges: [
    { id: "fe1", source: "f1", target: "f3" },
    { id: "fe2", source: "f2", target: "f3" },
    { id: "fe3", source: "f1", target: "f4" },
    { id: "fe4", source: "f2", target: "f4" },
    { id: "fe5", source: "f3", target: "f5" },
    { id: "fe6", source: "f3", target: "f6" },
    { id: "fe7", source: "f4", target: "f7" },
    { id: "fe8", source: "f4", target: "f8" },
  ],
};

const familyTreeGenealogy: DiagramTemplate = {
  id: "family-genealogy",
  title: "Genealogy Chart",
  description: "Deep ancestry research template spanning 4 generations.",
  category: "Family Trees",
  color: "#c4b5fd",
  nodeCount: 12,
  previewNodes: [
    { x: 50, y: 8, w: 60 },
    { x: 28, y: 32, w: 55 }, { x: 72, y: 32, w: 55 },
    { x: 18, y: 58, w: 50 }, { x: 38, y: 58, w: 50 }, { x: 62, y: 58, w: 50 }, { x: 82, y: 58, w: 50 },
    { x: 10, y: 82, w: 40 }, { x: 28, y: 82, w: 40 }, { x: 48, y: 82, w: 40 }, { x: 68, y: 82, w: 40 }, { x: 88, y: 82, w: 40 },
  ],
  previewEdges: [[0,1],[0,2],[1,3],[1,4],[2,5],[2,6],[3,7],[3,8],[4,9],[5,10],[6,11]],
  nodes: [
    { id: "g0", label: "Ancestor\nWilliam", shape: "rounded", bgColor: "#4c1d95" },
    { id: "g1", label: "Son\nEdward", shape: "rect", bgColor: "#5b21b6" },
    { id: "g2", label: "Daughter\nAnne", shape: "rect", bgColor: "#5b21b6" },
    { id: "g3", label: "Grandson\nCharles", shape: "rect", bgColor: "#6d28d9" },
    { id: "g4", label: "Granddaughter\nElizabeth", shape: "rect", bgColor: "#6d28d9" },
    { id: "g5", label: "Grandson\nHenry", shape: "rect", bgColor: "#6d28d9" },
    { id: "g6", label: "Granddaughter\nCatherine", shape: "rect", bgColor: "#6d28d9" },
    { id: "g7", label: "Arthur", shape: "rounded", bgColor: "#080808" },
    { id: "g8", label: "Victoria", shape: "rounded", bgColor: "#080808" },
    { id: "g9", label: "George", shape: "rounded", bgColor: "#080808" },
    { id: "g10", label: "Richard", shape: "rounded", bgColor: "#080808" },
    { id: "g11", label: "Margaret", shape: "rounded", bgColor: "#080808" },
  ],
  edges: [
    { id: "ge0", source: "g0", target: "g1" },
    { id: "ge1", source: "g0", target: "g2" },
    { id: "ge2", source: "g1", target: "g3" },
    { id: "ge3", source: "g1", target: "g4" },
    { id: "ge4", source: "g2", target: "g5" },
    { id: "ge5", source: "g2", target: "g6" },
    { id: "ge6", source: "g3", target: "g7" },
    { id: "ge7", source: "g3", target: "g8" },
    { id: "ge8", source: "g4", target: "g9" },
    { id: "ge9", source: "g5", target: "g10" },
    { id: "ge10", source: "g6", target: "g11" },
  ],
};

const familyTreeDescendants: DiagramTemplate = {
  id: "family-descendants",
  title: "Descendants Chart",
  description: "Track all descendants from a single common ancestor.",
  category: "Family Trees",
  color: "#8b5cf6",
  nodeCount: 10,
  previewNodes: [
    { x: 50, y: 10, w: 70 },
    { x: 25, y: 38, w: 60 }, { x: 75, y: 38, w: 60 },
    { x: 12, y: 68, w: 52 }, { x: 38, y: 68, w: 52 }, { x: 62, y: 68, w: 52 }, { x: 88, y: 68, w: 52 },
  ],
  previewEdges: [[0,1],[0,2],[1,3],[1,4],[2,5],[2,6]],
  nodes: [
    { id: "d0", label: "Founder\nAlbert", shape: "hexagon", bgColor: "#4c1d95" },
    { id: "d1", label: "Branch A\nThomas", shape: "rounded", bgColor: "#5b21b6" },
    { id: "d2", label: "Branch B\nEleanor", shape: "rounded", bgColor: "#5b21b6" },
    { id: "d3", label: "Oliver", shape: "rect", bgColor: "#6d28d9" },
    { id: "d4", label: "Evelyn", shape: "rect", bgColor: "#6d28d9" },
    { id: "d5", label: "Harold", shape: "rect", bgColor: "#6d28d9" },
    { id: "d6", label: "Dorothy", shape: "rect", bgColor: "#6d28d9" },
    { id: "d7", label: "Walter", shape: "rounded", bgColor: "#080808" },
    { id: "d8", label: "Florence", shape: "rounded", bgColor: "#080808" },
    { id: "d9", label: "Bernard", shape: "rounded", bgColor: "#080808" },
  ],
  edges: [
    { id: "dd0", source: "d0", target: "d1" },
    { id: "dd1", source: "d0", target: "d2" },
    { id: "dd2", source: "d1", target: "d3" },
    { id: "dd3", source: "d1", target: "d4" },
    { id: "dd4", source: "d2", target: "d5" },
    { id: "dd5", source: "d2", target: "d6" },
    { id: "dd6", source: "d3", target: "d7" },
    { id: "dd7", source: "d4", target: "d8" },
    { id: "dd8", source: "d6", target: "d9" },
  ],
};

// ── Org Charts ────────────────────────────────────────────────────────────────

const orgChartCompany: DiagramTemplate = {
  id: "org-company",
  title: "Company Hierarchy",
  description: "Full company org chart from CEO to individual contributors.",
  category: "Org Charts",
  color: "#67e8f9",
  nodeCount: 10,
  previewNodes: [
    { x: 50, y: 10, w: 60 },
    { x: 25, y: 35, w: 58 }, { x: 50, y: 35, w: 58 }, { x: 75, y: 35, w: 58 },
    { x: 12, y: 65, w: 52 }, { x: 37, y: 65, w: 52 }, { x: 63, y: 65, w: 52 }, { x: 88, y: 65, w: 52 },
  ],
  previewEdges: [[0,1],[0,2],[0,3],[1,4],[1,5],[2,6],[3,7]],
  nodes: [
    { id: "o0", label: "CEO\nJane Williams", shape: "rounded", bgColor: "#164e63" },
    { id: "o1", label: "VP Engineering\nMike Chen", shape: "rect", bgColor: "#0e7490" },
    { id: "o2", label: "VP Marketing\nSarah Lee", shape: "rect", bgColor: "#0e7490" },
    { id: "o3", label: "VP Sales\nDavid Kim", shape: "rect", bgColor: "#0e7490" },
    { id: "o4", label: "Eng Manager\nAlex Torres", shape: "rect", bgColor: "#0891b2" },
    { id: "o5", label: "Sr. Engineer\nCasey Park", shape: "rect", bgColor: "#0891b2" },
    { id: "o6", label: "Marketing Lead\nJordan Davis", shape: "rect", bgColor: "#0891b2" },
    { id: "o7", label: "Sales Lead\nTaylor Brown", shape: "rect", bgColor: "#0891b2" },
    { id: "o8", label: "Engineer\nRobin Walsh", shape: "rounded", bgColor: "#06b6d4" },
    { id: "o9", label: "Engineer\nMorgan Hill", shape: "rounded", bgColor: "#06b6d4" },
  ],
  edges: [
    { id: "oe0", source: "o0", target: "o1" },
    { id: "oe1", source: "o0", target: "o2" },
    { id: "oe2", source: "o0", target: "o3" },
    { id: "oe3", source: "o1", target: "o4" },
    { id: "oe4", source: "o1", target: "o5" },
    { id: "oe5", source: "o2", target: "o6" },
    { id: "oe6", source: "o3", target: "o7" },
    { id: "oe7", source: "o4", target: "o8" },
    { id: "oe8", source: "o4", target: "o9" },
  ],
};

const orgChartDepartment: DiagramTemplate = {
  id: "org-department",
  title: "Department Structure",
  description: "Single department breakdown with team leads and members.",
  category: "Org Charts",
  color: "#38bdf8",
  nodeCount: 9,
  previewNodes: [
    { x: 50, y: 12, w: 70 },
    { x: 25, y: 40, w: 62 }, { x: 75, y: 40, w: 62 },
    { x: 12, y: 70, w: 52 }, { x: 38, y: 70, w: 52 }, { x: 62, y: 70, w: 52 }, { x: 88, y: 70, w: 52 },
  ],
  previewEdges: [[0,1],[0,2],[1,3],[1,4],[2,5],[2,6]],
  nodes: [
    { id: "dep0", label: "Director\nChris Morgan", shape: "rounded", bgColor: "#075985" },
    { id: "dep1", label: "Team Lead\nProduct", shape: "rect", bgColor: "#0369a1" },
    { id: "dep2", label: "Team Lead\nDesign", shape: "rect", bgColor: "#0369a1" },
    { id: "dep3", label: "Product Manager\nAlex", shape: "rect", bgColor: "#0284c7" },
    { id: "dep4", label: "Product Analyst\nJordan", shape: "rect", bgColor: "#0284c7" },
    { id: "dep5", label: "UX Designer\nSam", shape: "rect", bgColor: "#0284c7" },
    { id: "dep6", label: "Visual Designer\nLee", shape: "rect", bgColor: "#0284c7" },
    { id: "dep7", label: "Researcher\nTaylor", shape: "rounded", bgColor: "#0ea5e9" },
    { id: "dep8", label: "Coordinator\nPat", shape: "rounded", bgColor: "#0ea5e9" },
  ],
  edges: [
    { id: "depe0", source: "dep0", target: "dep1" },
    { id: "depe1", source: "dep0", target: "dep2" },
    { id: "depe2", source: "dep1", target: "dep3" },
    { id: "depe3", source: "dep1", target: "dep4" },
    { id: "depe4", source: "dep2", target: "dep5" },
    { id: "depe5", source: "dep2", target: "dep6" },
    { id: "depe6", source: "dep3", target: "dep7" },
    { id: "depe7", source: "dep4", target: "dep8" },
  ],
};

const orgChartProject: DiagramTemplate = {
  id: "org-project",
  title: "Project Team",
  description: "Cross-functional project team with role and responsibility mapping.",
  category: "Org Charts",
  color: "#7dd3fc",
  nodeCount: 8,
  previewNodes: [
    { x: 50, y: 15, w: 70 },
    { x: 20, y: 45, w: 65 }, { x: 50, y: 45, w: 65 }, { x: 80, y: 45, w: 65 },
    { x: 20, y: 78, w: 58 }, { x: 50, y: 78, w: 58 }, { x: 80, y: 78, w: 58 },
  ],
  previewEdges: [[0,1],[0,2],[0,3],[1,4],[2,5],[3,6]],
  nodes: [
    { id: "pt0", label: "Project Manager\nRobin Chen", shape: "hexagon", bgColor: "#0c4a6e" },
    { id: "pt1", label: "Engineering\nLead", shape: "rounded", bgColor: "#075985" },
    { id: "pt2", label: "Design\nLead", shape: "rounded", bgColor: "#075985" },
    { id: "pt3", label: "QA\nLead", shape: "rounded", bgColor: "#075985" },
    { id: "pt4", label: "Frontend Dev", shape: "rect", bgColor: "#0369a1" },
    { id: "pt5", label: "Backend Dev", shape: "rect", bgColor: "#0369a1" },
    { id: "pt6", label: "UX Designer", shape: "rect", bgColor: "#0369a1" },
    { id: "pt7", label: "QA Engineer", shape: "rect", bgColor: "#0369a1" },
  ],
  edges: [
    { id: "pte0", source: "pt0", target: "pt1" },
    { id: "pte1", source: "pt0", target: "pt2" },
    { id: "pte2", source: "pt0", target: "pt3" },
    { id: "pte3", source: "pt1", target: "pt4" },
    { id: "pte4", source: "pt1", target: "pt5" },
    { id: "pte5", source: "pt2", target: "pt6" },
    { id: "pte6", source: "pt3", target: "pt7" },
  ],
};

// ── Mind Maps ─────────────────────────────────────────────────────────────────

const mindMapProject: DiagramTemplate = {
  id: "mindmap-project",
  title: "Project Planning",
  description: "Break down a project into phases, tasks, and milestones.",
  category: "Mind Maps",
  color: "#f9a8d4",
  nodeCount: 13,
  previewNodes: [
    { x: 50, y: 50, w: 70 },
    { x: 15, y: 20, w: 60 }, { x: 85, y: 20, w: 60 },
    { x: 15, y: 80, w: 60 }, { x: 85, y: 80, w: 60 }, { x: 50, y: 10, w: 60 },
    { x: 8, y: 50, w: 55 }, { x: 92, y: 50, w: 55 },
  ],
  previewEdges: [[0,1],[0,2],[0,3],[0,4],[0,5],[0,6],[0,7]],
  nodes: [
    { id: "mm0", label: "Project\nGoal", shape: "rounded", bgColor: "#831843" },
    { id: "mm1", label: "Planning\nPhase", shape: "rect", bgColor: "#9d174d" },
    { id: "mm2", label: "Development\nPhase", shape: "rect", bgColor: "#9d174d" },
    { id: "mm3", label: "Testing\nPhase", shape: "rect", bgColor: "#9d174d" },
    { id: "mm4", label: "Launch", shape: "rect", bgColor: "#9d174d" },
    { id: "mm5", label: "Requirements", shape: "rounded", bgColor: "#be185d" },
    { id: "mm6", label: "Design", shape: "rounded", bgColor: "#be185d" },
    { id: "mm7", label: "Sprint 1", shape: "rounded", bgColor: "#db2777" },
    { id: "mm8", label: "Sprint 2", shape: "rounded", bgColor: "#db2777" },
    { id: "mm9", label: "Unit Tests", shape: "rounded", bgColor: "#db2777" },
    { id: "mm10", label: "Integration", shape: "rounded", bgColor: "#db2777" },
    { id: "mm11", label: "Marketing", shape: "rounded", bgColor: "#ec4899" },
    { id: "mm12", label: "Deployment", shape: "rounded", bgColor: "#ec4899" },
  ],
  edges: [
    { id: "mme0", source: "mm0", target: "mm1" },
    { id: "mme1", source: "mm0", target: "mm2" },
    { id: "mme2", source: "mm0", target: "mm3" },
    { id: "mme3", source: "mm0", target: "mm4" },
    { id: "mme4", source: "mm1", target: "mm5" },
    { id: "mme5", source: "mm1", target: "mm6" },
    { id: "mme6", source: "mm2", target: "mm7" },
    { id: "mme7", source: "mm2", target: "mm8" },
    { id: "mme8", source: "mm3", target: "mm9" },
    { id: "mme9", source: "mm3", target: "mm10" },
    { id: "mme10", source: "mm4", target: "mm11" },
    { id: "mme11", source: "mm4", target: "mm12" },
  ],
};

const mindMapBrainstorm: DiagramTemplate = {
  id: "mindmap-brainstorm",
  title: "Brainstorming Session",
  description: "Open-ended brainstorm canvas with idea clusters.",
  category: "Mind Maps",
  color: "#e879f9",
  nodeCount: 11,
  previewNodes: [
    { x: 50, y: 50, w: 70 },
    { x: 18, y: 22, w: 62 }, { x: 82, y: 22, w: 62 },
    { x: 18, y: 78, w: 62 }, { x: 82, y: 78, w: 62 },
    { x: 50, y: 15, w: 60 }, { x: 50, y: 85, w: 60 },
  ],
  previewEdges: [[0,1],[0,2],[0,3],[0,4],[0,5],[0,6]],
  nodes: [
    { id: "br0", label: "Central\nIdea", shape: "circle", bgColor: "#701a75" },
    { id: "br1", label: "Idea\nCluster A", shape: "cloud", bgColor: "#86198f" },
    { id: "br2", label: "Idea\nCluster B", shape: "cloud", bgColor: "#86198f" },
    { id: "br3", label: "Idea\nCluster C", shape: "cloud", bgColor: "#86198f" },
    { id: "br4", label: "Idea\nCluster D", shape: "cloud", bgColor: "#86198f" },
    { id: "br5", label: "Sub-idea 1", shape: "rounded", bgColor: "#a21caf" },
    { id: "br6", label: "Sub-idea 2", shape: "rounded", bgColor: "#a21caf" },
    { id: "br7", label: "Sub-idea 3", shape: "rounded", bgColor: "#a21caf" },
    { id: "br8", label: "Sub-idea 4", shape: "rounded", bgColor: "#a21caf" },
    { id: "br9", label: "Action 1", shape: "parallelogram", bgColor: "#c026d3" },
    { id: "br10", label: "Action 2", shape: "parallelogram", bgColor: "#c026d3" },
  ],
  edges: [
    { id: "bre0", source: "br0", target: "br1" },
    { id: "bre1", source: "br0", target: "br2" },
    { id: "bre2", source: "br0", target: "br3" },
    { id: "bre3", source: "br0", target: "br4" },
    { id: "bre4", source: "br1", target: "br5" },
    { id: "bre5", source: "br1", target: "br6" },
    { id: "bre6", source: "br2", target: "br7" },
    { id: "bre7", source: "br3", target: "br8" },
    { id: "bre8", source: "br4", target: "br9" },
    { id: "bre9", source: "br4", target: "br10" },
  ],
};

const mindMapStudy: DiagramTemplate = {
  id: "mindmap-study",
  title: "Study Notes",
  description: "Organize study material into topics, subtopics, and key facts.",
  category: "Mind Maps",
  color: "#d946ef",
  nodeCount: 10,
  previewNodes: [
    { x: 50, y: 50, w: 65 },
    { x: 20, y: 20, w: 58 }, { x: 80, y: 20, w: 58 },
    { x: 20, y: 80, w: 58 }, { x: 80, y: 80, w: 58 },
    { x: 10, y: 48, w: 55 }, { x: 90, y: 48, w: 55 },
  ],
  previewEdges: [[0,1],[0,2],[0,3],[0,4],[0,5],[0,6]],
  nodes: [
    { id: "st0", label: "Subject\nMain Topic", shape: "hexagon", bgColor: "#701a75" },
    { id: "st1", label: "Chapter 1\nIntro", shape: "rect", bgColor: "#86198f" },
    { id: "st2", label: "Chapter 2\nCore Concepts", shape: "rect", bgColor: "#86198f" },
    { id: "st3", label: "Chapter 3\nApplications", shape: "rect", bgColor: "#86198f" },
    { id: "st4", label: "Key Terms", shape: "rounded", bgColor: "#a21caf" },
    { id: "st5", label: "Formulas", shape: "rounded", bgColor: "#a21caf" },
    { id: "st6", label: "Examples", shape: "rounded", bgColor: "#a21caf" },
    { id: "st7", label: "Practice Q1", shape: "parallelogram", bgColor: "#c026d3" },
    { id: "st8", label: "Practice Q2", shape: "parallelogram", bgColor: "#c026d3" },
    { id: "st9", label: "Summary", shape: "cloud", bgColor: "#d946ef" },
  ],
  edges: [
    { id: "ste0", source: "st0", target: "st1" },
    { id: "ste1", source: "st0", target: "st2" },
    { id: "ste2", source: "st0", target: "st3" },
    { id: "ste3", source: "st1", target: "st4" },
    { id: "ste4", source: "st2", target: "st5" },
    { id: "ste5", source: "st2", target: "st6" },
    { id: "ste6", source: "st3", target: "st7" },
    { id: "ste7", source: "st3", target: "st8" },
    { id: "ste8", source: "st0", target: "st9" },
  ],
};

// ── Network Diagrams ──────────────────────────────────────────────────────────

const networkSystemArch: DiagramTemplate = {
  id: "network-arch",
  title: "System Architecture",
  description: "3-tier web application architecture with load balancers and databases.",
  category: "Network Diagrams",
  color: "#86efac",
  nodeCount: 9,
  previewNodes: [
    { x: 50, y: 10, w: 78 },
    { x: 50, y: 38, w: 65 },
    { x: 25, y: 65, w: 60 }, { x: 50, y: 65, w: 60 }, { x: 75, y: 65, w: 60 },
    { x: 50, y: 90, w: 70 },
  ],
  previewEdges: [[0,1],[1,2],[1,3],[1,4],[2,5],[3,5],[4,5]],
  nodes: [
    { id: "na0", label: "Internet /\nUsers", shape: "cloud", bgColor: "#052e16" },
    { id: "na1", label: "Load\nBalancer", shape: "hexagon", bgColor: "#14532d" },
    { id: "na2", label: "App Server 1\n:3001", shape: "cylinder", bgColor: "#166534" },
    { id: "na3", label: "App Server 2\n:3002", shape: "cylinder", bgColor: "#166534" },
    { id: "na4", label: "App Server 3\n:3003", shape: "cylinder", bgColor: "#166534" },
    { id: "na5", label: "Primary DB\nPostgres", shape: "cylinder", bgColor: "#15803d" },
    { id: "na6", label: "Replica DB\nRead-only", shape: "cylinder", bgColor: "#15803d" },
    { id: "na7", label: "Cache Layer\nRedis", shape: "hexagon", bgColor: "#16a34a" },
    { id: "na8", label: "CDN\nStatic Assets", shape: "cloud", bgColor: "#16a34a" },
  ],
  edges: [
    { id: "nae0", source: "na0", target: "na1", label: "HTTPS" },
    { id: "nae1", source: "na1", target: "na2" },
    { id: "nae2", source: "na1", target: "na3" },
    { id: "nae3", source: "na1", target: "na4" },
    { id: "nae4", source: "na2", target: "na5" },
    { id: "nae5", source: "na3", target: "na5" },
    { id: "nae6", source: "na4", target: "na5" },
    { id: "nae7", source: "na5", target: "na6" },
    { id: "nae8", source: "na2", target: "na7" },
    { id: "nae9", source: "na0", target: "na8" },
  ],
};

const networkSocial: DiagramTemplate = {
  id: "network-social",
  title: "Social Network",
  description: "Visualize relationships between people, groups, and communities.",
  category: "Network Diagrams",
  color: "#4ade80",
  nodeCount: 9,
  previewNodes: [
    { x: 50, y: 50, w: 62 },
    { x: 20, y: 20, w: 58 }, { x: 80, y: 20, w: 58 },
    { x: 15, y: 60, w: 58 }, { x: 50, y: 82, w: 58 }, { x: 85, y: 60, w: 58 },
    { x: 35, y: 35, w: 55 }, { x: 65, y: 35, w: 55 }, { x: 50, y: 10, w: 55 },
  ],
  previewEdges: [[0,1],[0,2],[0,3],[0,4],[0,5],[1,6],[2,7],[0,8]],
  nodes: [
    { id: "sn0", label: "Community\nHub", shape: "circle", bgColor: "#052e16" },
    { id: "sn1", label: "Alice\nDeveloper", shape: "rounded", bgColor: "#14532d" },
    { id: "sn2", label: "Bob\nDesigner", shape: "rounded", bgColor: "#14532d" },
    { id: "sn3", label: "Carol\nManager", shape: "rounded", bgColor: "#14532d" },
    { id: "sn4", label: "Dave\nAnalyst", shape: "rounded", bgColor: "#14532d" },
    { id: "sn5", label: "Eve\nMarketer", shape: "rounded", bgColor: "#14532d" },
    { id: "sn6", label: "Dev\nTeam", shape: "hexagon", bgColor: "#166534" },
    { id: "sn7", label: "Design\nTeam", shape: "hexagon", bgColor: "#166534" },
    { id: "sn8", label: "Leadership\nGroup", shape: "hexagon", bgColor: "#166534" },
  ],
  edges: [
    { id: "sne0", source: "sn0", target: "sn1" },
    { id: "sne1", source: "sn0", target: "sn2" },
    { id: "sne2", source: "sn0", target: "sn3" },
    { id: "sne3", source: "sn0", target: "sn4" },
    { id: "sne4", source: "sn0", target: "sn5" },
    { id: "sne5", source: "sn1", target: "sn6" },
    { id: "sne6", source: "sn2", target: "sn7" },
    { id: "sne7", source: "sn3", target: "sn8" },
    { id: "sne8", source: "sn0", target: "sn8" },
  ],
};

const networkIT: DiagramTemplate = {
  id: "network-it",
  title: "IT Infrastructure",
  description: "Data center layout with servers, switches, firewalls, and endpoints.",
  category: "Network Diagrams",
  color: "#22c55e",
  nodeCount: 10,
  previewNodes: [
    { x: 50, y: 10, w: 72 },
    { x: 25, y: 35, w: 65 }, { x: 75, y: 35, w: 65 },
    { x: 10, y: 65, w: 58 }, { x: 40, y: 65, w: 58 }, { x: 60, y: 65, w: 58 }, { x: 90, y: 65, w: 58 },
  ],
  previewEdges: [[0,1],[0,2],[1,3],[1,4],[2,5],[2,6]],
  nodes: [
    { id: "it0", label: "Firewall\nMain", shape: "hexagon", bgColor: "#052e16" },
    { id: "it1", label: "Core Switch\nLayer 3", shape: "rect", bgColor: "#14532d" },
    { id: "it2", label: "DMZ\nSwitch", shape: "rect", bgColor: "#14532d" },
    { id: "it3", label: "Web Server\n192.168.1.10", shape: "cylinder", bgColor: "#166534" },
    { id: "it4", label: "App Server\n192.168.1.20", shape: "cylinder", bgColor: "#166534" },
    { id: "it5", label: "DB Server\n192.168.1.30", shape: "cylinder", bgColor: "#166534" },
    { id: "it6", label: "Backup\nServer", shape: "cylinder", bgColor: "#166534" },
    { id: "it7", label: "Workstation\nCluster", shape: "rect", bgColor: "#15803d" },
    { id: "it8", label: "NAS\nStorage", shape: "cylinder", bgColor: "#15803d" },
    { id: "it9", label: "Monitoring\nNagios", shape: "cloud", bgColor: "#16a34a" },
  ],
  edges: [
    { id: "ite0", source: "it0", target: "it1" },
    { id: "ite1", source: "it0", target: "it2" },
    { id: "ite2", source: "it1", target: "it3" },
    { id: "ite3", source: "it1", target: "it4" },
    { id: "ite4", source: "it1", target: "it7" },
    { id: "ite5", source: "it2", target: "it5" },
    { id: "ite6", source: "it2", target: "it6" },
    { id: "ite7", source: "it4", target: "it5" },
    { id: "ite8", source: "it1", target: "it8" },
    { id: "ite9", source: "it9", target: "it0" },
  ],
};

// ── Flowcharts ────────────────────────────────────────────────────────────────

const flowchartLogin: DiagramTemplate = {
  id: "flow-login",
  title: "User Login Flow",
  description: "Authentication flow with credential validation and error handling.",
  category: "Flowcharts",
  color: "#fbbf24",
  nodeCount: 8,
  previewNodes: [
    { x: 50, y: 8, w: 42 },
    { x: 50, y: 28, w: 68 },
    { x: 50, y: 50, w: 55 },
    { x: 25, y: 72, w: 58 }, { x: 75, y: 72, w: 58 },
    { x: 75, y: 90, w: 58 },
    { x: 50, y: 90, w: 42 },
  ],
  previewEdges: [[0,1],[1,2],[2,3],[2,4],[4,5],[3,6]],
  nodes: [
    { id: "fl0", label: "Start", shape: "circle", bgColor: "#431407" },
    { id: "fl1", label: "Enter\nCredentials", shape: "process", bgColor: "#7c2d12" },
    { id: "fl2", label: "Credentials\nValid?", shape: "decision", bgColor: "#92400e" },
    { id: "fl3", label: "Login\nSuccessful", shape: "rounded", bgColor: "#78350f" },
    { id: "fl4", label: "Show Error\nMessage", shape: "rounded", bgColor: "#78350f" },
    { id: "fl5", label: "Retry\nAllowed?", shape: "decision", bgColor: "#92400e" },
    { id: "fl6", label: "Dashboard", shape: "process", bgColor: "#854d0e" },
    { id: "fl7", label: "End", shape: "circle", bgColor: "#431407" },
  ],
  edges: [
    { id: "fle0", source: "fl0", target: "fl1" },
    { id: "fle1", source: "fl1", target: "fl2" },
    { id: "fle2", source: "fl2", target: "fl3", label: "Yes" },
    { id: "fle3", source: "fl2", target: "fl4", label: "No" },
    { id: "fle4", source: "fl3", target: "fl6" },
    { id: "fle5", source: "fl4", target: "fl5" },
    { id: "fle6", source: "fl5", target: "fl1", label: "Yes" },
    { id: "fle7", source: "fl5", target: "fl7", label: "No" },
    { id: "fle8", source: "fl6", target: "fl7" },
  ],
};

const flowchartOrder: DiagramTemplate = {
  id: "flow-order",
  title: "Order Processing",
  description: "E-commerce order lifecycle from placement to fulfillment.",
  category: "Flowcharts",
  color: "#f59e0b",
  nodeCount: 10,
  previewNodes: [
    { x: 50, y: 7, w: 45 },
    { x: 50, y: 24, w: 68 },
    { x: 50, y: 42, w: 58 },
    { x: 25, y: 62, w: 56 }, { x: 75, y: 62, w: 56 },
    { x: 25, y: 80, w: 56 }, { x: 75, y: 80, w: 56 },
    { x: 50, y: 93, w: 45 },
  ],
  previewEdges: [[0,1],[1,2],[2,3],[2,4],[3,5],[4,6],[5,7],[6,7]],
  nodes: [
    { id: "fo0", label: "Start", shape: "circle", bgColor: "#451a03" },
    { id: "fo1", label: "Place Order", shape: "process", bgColor: "#7c2d12" },
    { id: "fo2", label: "Payment\nApproved?", shape: "decision", bgColor: "#92400e" },
    { id: "fo3", label: "Process\nPayment", shape: "process", bgColor: "#78350f" },
    { id: "fo4", label: "Payment\nFailed", shape: "rounded", bgColor: "#78350f" },
    { id: "fo5", label: "Pick & Pack\nItems", shape: "process", bgColor: "#854d0e" },
    { id: "fo6", label: "Notify\nCustomer", shape: "process", bgColor: "#854d0e" },
    { id: "fo7", label: "Ship\nOrder", shape: "process", bgColor: "#a16207" },
    { id: "fo8", label: "Delivered", shape: "rounded", bgColor: "#a16207" },
    { id: "fo9", label: "End", shape: "circle", bgColor: "#451a03" },
  ],
  edges: [
    { id: "foe0", source: "fo0", target: "fo1" },
    { id: "foe1", source: "fo1", target: "fo2" },
    { id: "foe2", source: "fo2", target: "fo3", label: "Yes" },
    { id: "foe3", source: "fo2", target: "fo4", label: "No" },
    { id: "foe4", source: "fo3", target: "fo5" },
    { id: "foe5", source: "fo4", target: "fo6" },
    { id: "foe6", source: "fo5", target: "fo7" },
    { id: "foe7", source: "fo7", target: "fo8" },
    { id: "foe8", source: "fo8", target: "fo9" },
    { id: "foe9", source: "fo6", target: "fo9" },
  ],
};

const flowchartSoftwareDev: DiagramTemplate = {
  id: "flow-sdlc",
  title: "Software Dev Lifecycle",
  description: "Agile software development process from planning to deployment.",
  category: "Flowcharts",
  color: "#d97706",
  nodeCount: 9,
  previewNodes: [
    { x: 50, y: 8, w: 55 },
    { x: 50, y: 25, w: 68 },
    { x: 50, y: 43, w: 60 },
    { x: 50, y: 62, w: 68 },
    { x: 50, y: 80, w: 60 },
  ],
  previewEdges: [[0,1],[1,2],[2,3],[3,4]],
  nodes: [
    { id: "sd0", label: "Requirements\nGathering", shape: "process", bgColor: "#451a03" },
    { id: "sd1", label: "System\nDesign", shape: "process", bgColor: "#7c2d12" },
    { id: "sd2", label: "Implementation\n& Coding", shape: "process", bgColor: "#92400e" },
    { id: "sd3", label: "Testing &\nQA Review", shape: "process", bgColor: "#78350f" },
    { id: "sd4", label: "Tests\nPass?", shape: "decision", bgColor: "#854d0e" },
    { id: "sd5", label: "Fix Bugs &\nRegression", shape: "rounded", bgColor: "#a16207" },
    { id: "sd6", label: "Staging\nDeployment", shape: "process", bgColor: "#a16207" },
    { id: "sd7", label: "Production\nDeployment", shape: "process", bgColor: "#ca8a04" },
    { id: "sd8", label: "Monitor &\nMaintain", shape: "cloud", bgColor: "#ca8a04" },
  ],
  edges: [
    { id: "sde0", source: "sd0", target: "sd1" },
    { id: "sde1", source: "sd1", target: "sd2" },
    { id: "sde2", source: "sd2", target: "sd3" },
    { id: "sde3", source: "sd3", target: "sd4" },
    { id: "sde4", source: "sd4", target: "sd5", label: "No" },
    { id: "sde5", source: "sd5", target: "sd3" },
    { id: "sde6", source: "sd4", target: "sd6", label: "Yes" },
    { id: "sde7", source: "sd6", target: "sd7" },
    { id: "sde8", source: "sd7", target: "sd8" },
  ],
};

const flowchartDecision: DiagramTemplate = {
  id: "flow-decision",
  title: "Decision Tree",
  description: "Structured decision-making framework with branching outcomes.",
  category: "Flowcharts",
  color: "#fcd34d",
  nodeCount: 11,
  previewNodes: [
    { x: 50, y: 10, w: 62 },
    { x: 50, y: 30, w: 55 },
    { x: 25, y: 52, w: 55 }, { x: 75, y: 52, w: 55 },
    { x: 12, y: 74, w: 50 }, { x: 38, y: 74, w: 50 }, { x: 62, y: 74, w: 50 }, { x: 88, y: 74, w: 50 },
  ],
  previewEdges: [[0,1],[1,2],[1,3],[2,4],[2,5],[3,6],[3,7]],
  nodes: [
    { id: "dt0", label: "Start\nDecision", shape: "circle", bgColor: "#431407" },
    { id: "dt1", label: "Primary\nQuestion?", shape: "decision", bgColor: "#7c2d12" },
    { id: "dt2", label: "Option A\nQuestion?", shape: "decision", bgColor: "#92400e" },
    { id: "dt3", label: "Option B\nQuestion?", shape: "decision", bgColor: "#92400e" },
    { id: "dt4", label: "Outcome\nA1", shape: "rounded", bgColor: "#78350f" },
    { id: "dt5", label: "Outcome\nA2", shape: "rounded", bgColor: "#78350f" },
    { id: "dt6", label: "Outcome\nB1", shape: "rounded", bgColor: "#78350f" },
    { id: "dt7", label: "Outcome\nB2", shape: "rounded", bgColor: "#78350f" },
    { id: "dt8", label: "Action A1", shape: "process", bgColor: "#854d0e" },
    { id: "dt9", label: "Action A2", shape: "process", bgColor: "#854d0e" },
    { id: "dt10", label: "Action B", shape: "process", bgColor: "#854d0e" },
  ],
  edges: [
    { id: "dte0", source: "dt0", target: "dt1" },
    { id: "dte1", source: "dt1", target: "dt2", label: "Yes" },
    { id: "dte2", source: "dt1", target: "dt3", label: "No" },
    { id: "dte3", source: "dt2", target: "dt4", label: "Yes" },
    { id: "dte4", source: "dt2", target: "dt5", label: "No" },
    { id: "dte5", source: "dt3", target: "dt6", label: "Yes" },
    { id: "dte6", source: "dt3", target: "dt7", label: "No" },
    { id: "dte7", source: "dt4", target: "dt8" },
    { id: "dte8", source: "dt5", target: "dt9" },
    { id: "dte9", source: "dt6", target: "dt10" },
    { id: "dte10", source: "dt7", target: "dt10" },
  ],
};

// ── ER Diagrams ────────────────────────────────────────────────────────────────

const erDiagramEcommerce: DiagramTemplate = {
  id: "er-ecommerce",
  title: "E-Commerce Schema",
  description: "Core e-commerce entities: Users, Products, Orders, and relationships.",
  category: "ER Diagrams",
  color: "#fca5a5",
  nodeCount: 8,
  previewNodes: [
    { x: 50, y: 10, w: 68 },
    { x: 25, y: 38, w: 62 },
    { x: 75, y: 38, w: 62 },
    { x: 15, y: 68, w: 60 },
    { x: 50, y: 68, w: 60 },
    { x: 85, y: 68, w: 60 },
    { x: 50, y: 90, w: 60 },
  ],
  previewEdges: [[0,1],[1,3],[1,4],[0,2],[2,5],[2,6],[4,7]],
  nodes: [
    { id: "er0", label: "User\nPK: id", shape: "rect", bgColor: "#7f1d1d" },
    { id: "er1", label: "Order\nPK: id", shape: "rect", bgColor: "#991b1b" },
    { id: "er2", label: "Product\nPK: id", shape: "rect", bgColor: "#991b1b" },
    { id: "er3", label: "OrderItem\nPK: id", shape: "rect", bgColor: "#b91c1c" },
    { id: "er4", label: "Payment\nPK: id", shape: "rect", bgColor: "#b91c1c" },
    { id: "er5", label: "Category\nPK: id", shape: "rect", bgColor: "#dc2626" },
    { id: "er6", label: "Review\nPK: id", shape: "rect", bgColor: "#dc2626" },
    { id: "er7", label: "Shipping\nPK: id", shape: "rect", bgColor: "#ef4444" },
  ],
  edges: [
    { id: "ere0", source: "er0", target: "er1", label: "1:N" },
    { id: "ere1", source: "er1", target: "er3", label: "1:N" },
    { id: "ere2", source: "er2", target: "er3", label: "1:N" },
    { id: "ere3", source: "er1", target: "er4", label: "1:1" },
    { id: "ere4", source: "er2", target: "er5", label: "N:1" },
    { id: "ere5", source: "er0", target: "er6", label: "1:N" },
    { id: "ere6", source: "er2", target: "er6", label: "1:N" },
    { id: "ere7", source: "er1", target: "er7", label: "1:1" },
  ],
};

const erDiagramSocial: DiagramTemplate = {
  id: "er-social",
  title: "Social Media Schema",
  description: "Social platform entities: Users, Posts, Comments, Likes, and Follows.",
  category: "ER Diagrams",
  color: "#fdba74",
  nodeCount: 7,
  previewNodes: [
    { x: 50, y: 10, w: 70 },
    { x: 30, y: 40, w: 65 },
    { x: 70, y: 40, w: 65 },
    { x: 15, y: 72, w: 60 },
    { x: 50, y: 72, w: 60 },
    { x: 85, y: 72, w: 60 },
  ],
  previewEdges: [[0,1],[1,3],[1,4],[0,2],[2,5]],
  nodes: [
    { id: "ers0", label: "User\nPK: id", shape: "rect", bgColor: "#7c2d12" },
    { id: "ers1", label: "Post\nPK: id", shape: "rect", bgColor: "#9a3412" },
    { id: "ers2", label: "Message\nPK: id", shape: "rect", bgColor: "#9a3412" },
    { id: "ers3", label: "Comment\nPK: id", shape: "rect", bgColor: "#c2410c" },
    { id: "ers4", label: "Like\nPK: id", shape: "rect", bgColor: "#c2410c" },
    { id: "ers5", label: "Follow\nPK: (follower,followee)", shape: "rect", bgColor: "#ea580c" },
    { id: "ers6", label: "Notification\nPK: id", shape: "rect", bgColor: "#f97316" },
  ],
  edges: [
    { id: "erse0", source: "ers0", target: "ers1", label: "1:N" },
    { id: "erse1", source: "ers1", target: "ers3", label: "1:N" },
    { id: "erse2", source: "ers1", target: "ers4", label: "1:N" },
    { id: "erse3", source: "ers0", target: "ers4", label: "1:N" },
    { id: "erse4", source: "ers0", target: "ers5", label: "1:N" },
    { id: "erse5", source: "ers0", target: "ers6", label: "1:N" },
    { id: "erse6", source: "ers0", target: "ers2", label: "1:N" },
  ],
};

const erDiagramSaaS: DiagramTemplate = {
  id: "er-saas",
  title: "SaaS Platform Schema",
  description: "Multi-tenant SaaS schema with workspaces, teams, and subscriptions.",
  category: "ER Diagrams",
  color: "#d9f99d",
  nodeCount: 9,
  previewNodes: [
    { x: 50, y: 10, w: 72 },
    { x: 30, y: 35, w: 62 },
    { x: 70, y: 35, w: 62 },
    { x: 15, y: 62, w: 58 },
    { x: 50, y: 62, w: 58 },
    { x: 85, y: 62, w: 58 },
    { x: 30, y: 85, w: 55 },
    { x: 70, y: 85, w: 55 },
  ],
  previewEdges: [[0,1],[0,2],[1,3],[1,4],[2,5],[4,6],[4,7]],
  nodes: [
    { id: "ersa0", label: "Workspace\nPK: id", shape: "rect", bgColor: "#14532d" },
    { id: "ersa1", label: "Team\nPK: id", shape: "rect", bgColor: "#166534" },
    { id: "ersa2", label: "Subscription\nPK: id", shape: "rect", bgColor: "#166534" },
    { id: "ersa3", label: "User\nPK: id", shape: "rect", bgColor: "#15803d" },
    { id: "ersa4", label: "Project\nPK: id", shape: "rect", bgColor: "#15803d" },
    { id: "ersa5", label: "Invoice\nPK: id", shape: "rect", bgColor: "#15803d" },
    { id: "ersa6", label: "Task\nPK: id", shape: "rect", bgColor: "#16a34a" },
    { id: "ersa7", label: "Invitation\nPK: id", shape: "rect", bgColor: "#16a34a" },
    { id: "ersa8", label: "Plan\nPK: id", shape: "rect", bgColor: "#22c55e" },
  ],
  edges: [
    { id: "ersae0", source: "ersa0", target: "ersa1", label: "1:N" },
    { id: "ersae1", source: "ersa1", target: "ersa3", label: "N:M" },
    { id: "ersae2", source: "ersa1", target: "ersa4", label: "1:N" },
    { id: "ersae3", source: "ersa4", target: "ersa6", label: "1:N" },
    { id: "ersae4", source: "ersa2", target: "ersa5", label: "1:N" },
    { id: "ersae5", source: "ersa0", target: "ersa2", label: "1:1" },
    { id: "ersae6", source: "ersa1", target: "ersa7", label: "1:N" },
    { id: "ersae7", source: "ersa2", target: "ersa8", label: "N:1" },
  ],
};

export const DIAGRAM_TEMPLATES: DiagramTemplate[] = [
  familyTreeBasic,
  familyTreeGenealogy,
  familyTreeDescendants,
  orgChartCompany,
  orgChartDepartment,
  orgChartProject,
  mindMapProject,
  mindMapBrainstorm,
  mindMapStudy,
  networkSystemArch,
  networkSocial,
  networkIT,
  flowchartLogin,
  flowchartOrder,
  flowchartSoftwareDev,
  flowchartDecision,
  erDiagramEcommerce,
  erDiagramSocial,
  erDiagramSaaS,
];

export const TEMPLATE_CATEGORIES = ["All", "Family Trees", "Org Charts", "Mind Maps", "Network Diagrams", "Flowcharts", "ER Diagrams"];
